### PR TITLE
Add option to whitelist domain from containment

### LINKED ISSUE #104: Exclude accounts.google.com
Add an option to exclude accounts.google.com, like there is for YouTube etc. This should make it possible to use Google as SAML provider in combination with the Google Container add-on.

### PR DESCRIPTION
**Pull request by sents**
This pull request adds an option to include a list of whitelisted domains.
It is my first real pull request so I hope I am doing this right.

Note that this would fix #104.

### CODE REVIEW

**Comment by Perflyst** [comment]
Thanks! I will test your patch as soon as possible. Also it needs a quick rebase

@hackerncoder what do you think?

**Comment by sents** [comment]
I rebased it now.

I've noticed that pressing enter in the extension preferences triggers saving the preferences.
As the domains are separated by newlines there is no way to enter multiple domains right now.
I would propose to use ","  or ";" as separator. Both characters are not allowed as part of domain names.

**Comment by sents** [comment]
The whitelist option uses a textarea element now, so it is possible to enter multiple domains.

**Comment by hackerncoder** [comment]
> Thanks! I will test your patch as soon as possible. Also it needs a quick rebase
> 
> @hackerncoder what do you think?

This is some serious code, and somewhat out of my ballpark (especially since I don't have that much energy right now), but seems fine.

**Comment by hackerncoder** [comment]
I tried it a little (google.com and blogger.com) and it seems fine.

**Comment by Perflyst** [comment]
@sents after hackerncoder's test I merged and released this feature. the containment is broken if the whitelisted google urls are empty

**Comment by Perflyst** [comment]
Additionally your popup is broken if the preferences are saved with empty whitelist
unknown

**Comment by hackerncoder** [comment]
> the containment is broken if the whitelisted google urls are empty -> by default the containment is broken

I can't reproduce this.

**Comment by sents** [comment]
I'll look into it

**Comment by sents** [comment]
Unfortunately I am not able to reproduce the bugs relating to the empty whitelist. I've tried my standard profile and a fresh profile without any other extensions.

**Comment by Perflyst** [comment]
In case you downloaded from AMO - I disabled version 1.5.2 there. If you download https://github.com/containers-everywhere/contain-google/releases/download/1.5.2/google_container-1.5.2.zip, create a fresh profile, use debug addons -> load temporary addon you should be able to reproduce it.

**Comment by sents** [comment]
I installed it on a different computer with Firefox 82 and could reproduce the bug. For some reason whitespace gets inserted into the setting when loading the settings for the first time. Thank you for your tip! I will now look into this.

**Comment by sents** [comment]
After the fix of #109 leaving the whitelist empty doesn't cause any problems anymore.
The problem was caused by the variables relating to whitelist being undefined, when loading the extension for the first time.
The checkboxes are also undefined, but this doesn't cause any problems because undefined works with boolean operators.

**Pull request merged**
