### PR TITLE
#54 Add option to allow Google Oauth login.

### PR DESCRIPTION
**Pull request by herpiko**
Patch for #54. Just like `Ignore Youtube`, but for Oauth related.

### CODE REVIEW

**Comment by totokaka** [comment]
I'm unsure about this. As far as I understand, it will let a few Google Oauth endpoints out of the google container, and allow google to place it's logon cookie outside of the google container.

In my experience, using google to log in on other sites have worked quite nicely with this extension.

I don't have a problem with this PR being pulled, as I'm sure it solves the login flow for some sites, but I think the explanation and wording of the option should  be changed. Maybe:
> Allow Google login outside container
> Allow Google login forms outside of the google container. Fixes OAuth login for some sites. Allows google to set login cookie outside of the container

**Comment by chrstfer** [comment]
I just want to air my reservations about allowing google to set login cookies outside the container. Why allow google access outside the container, is it better than bringing the sites into the google container while a session managed by google is active on them? Even just manually adding websites into the container like you can with others seems safer to me. Am I wrong to be worried?

**Comment by Perflyst** [comment]
You both are correct. Thanks for the PR @herpiko but it would be better if the sites would open inside the container

**Comment by herpiko** [comment]
Ok. I'll fix this in another PR.

**Pull request closed without merging**
