### PR TITLE
Add blogspot domains.

### PR DESCRIPTION
**Pull request by palopezv**
Blogspot domains are geocoded and match, as far as I know, Google's country domains.

### CODE REVIEW

**Comment by Perflyst** [comment]
The url shortener domains are okay. Thank you!
Most of your blogspot domains don't exist. Where did you get all these domains?

**Comment by palopezv** [comment]
Copy, paste and replace on your domain list. I just went with the reasoning that Google creates a local top-level domain redirection for blogspot when they enter a profitable market. So, Europe, Asia and Latin America have their own domains. the rest I was lazy.

**Comment by Perflyst** [comment]
Please check which ones go and which don't. The unnecessary domains only increase the size of the addon which is not good for performance. It's best to work on your first commit.

**Comment by palopezv** [comment]
I have resubmitted this as a different pull request.

**Pull request closed without merging**
